[package]
name = "korp"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  "crates/korp_engine",
  "crates/korp_math"
]

[dependencies]
korp_engine = { path = "crates/korp_engine" }
korp_math = { path = "crates/korp_math" }

