[package]
name = "korp_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
pollster = "0.4.0"
wgpu = "27.0.1"
winit = "0.30.12"
korp_math = { path = "../korp_math" }
